---
title: "R Notebook"
output: html_notebook
---

```{r}
instalar <- function(paquete) {
  if (!require(paquete,character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)) {
    install.packages(as.character(paquete), dependecies = TRUE, repos = "http://cran.us.r-project.org")
    library(paquete, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)
  }
}

paquetes <- c("odbc","readr", "stringr", "dplyr", "tidyverse", "bookdown",
              "funModeling","magrittr")

lapply(paquetes, instalar)

```


```{r}
library(readr)

data <- read_csv("./../data/clean_casi_rotacion.csv")
```

```{r}
head(data)
```

```{r}
describe(data)
```


```{r}
data_integrity(data)
```

```{r}

colnames(data) <- tolower(colnames(data))

data <- data %>% mutate(
  grupo_edad=0,
  grupo_edad = case_when(
    edad < 28 ~  1,
    edad > 47 ~ 3,
    TRUE ~ 2
  )
)

data$rotacion <- data$target

data <- data %>% mutate(
  grupo_sueldo=0,
  grupo_sueldo = case_when(
    sueldo_prom < 2000 ~  1,
    sueldo_prom  > 10000 ~ 3,
    TRUE ~ 2
  )
)

ggplot(data, aes(group = factor(rotacion), fill = factor(rotacion), grupo_edad)) + 
  geom_bar() 

ggplot(data, aes(group = factor(rotacion), fill = factor(rotacion),grupo_sueldo)) + 
  geom_bar() +
  facet_grid(~grupo_edad)

ggplot(data, aes(x = factor(rotacion), color = factor(rotacion),y = edad)) + 
 geom_boxplot()


```


```{r}
colnames(datos)
```


```{r}
datos <- data
datos<-as.matrix(datos)

n<-dim(datos)[1]
y<- datos$rotacion
y_standard <- y - 1

#Variables explicativas
#Categoricas
anestesia <- datos$Anestesia
complica <- datos$Complica
estado_c <- datos$Estado_civil
forma_nac <- datos$Forma_nac
hospital <- datos$Hospital
ind_ces <- datos$riesgo
monitoreo <- datos$Monitoreo
escolaridad <- datos$Escolaridad 

#Continuas
edad <- as.vector(scale(data$edad))
num_ventas <- as.vector(scale(datos$num_ventas))
num_trabajos_previos <- as.vector(scale(datos$num_trabajos_previos))
sueldo_prom <- as.vector(scale(datos$sueldo_prom)) 

```


# Modelo simple

```{r}
data<-list("n"=n,"y"=y_standard,"anestesia"= anestesia,
           "complica"=complica,"estado_c"=estado_c,
            "hospital"=hospital, "forma_nac"=forma_nac,
           "ind_ces"=ind_ces,"monitoreo"=monitoreo,
            "edad"=edad,"peso_madre"=peso_madre,
            "peso_prod"=peso_prod,"escolaridad"=escolaridad)

#-Definiendo inits-
inits<-function(){list(alpha=0,
                       b_an=rep(0,2),b_com=rep(0,2),
                       b_ec = rep(0,4), b_fn = rep(0,2),
                       b_ho = rep(0,7), b_ic = rep(0,2), 
                       b_mon = rep(0,2), b_edad = 0, 
                       b_pm = 0, b_pp = 0, b_esc = rep(0,4))}

#-Seleccionando parametros a monitorear-
parameters_complete<-c("alpha.est", 
              "b_an.est", "b_com.est", "b_ec.est", "b_ho.est",
              "b_ic.est", "b_mon.est", "b_edad", "b_pm","b_pp",
              "b_esc.est", "b_fn.est")


mod1.sim<-jags(data,inits,parameters_complete,model.file="prueba.txt",
              n.iter=8000,n.chains=2,n.burnin=2000,n.thin=2)
traceplot(mod1.sim)
out.dic<-mod1.sim$BUGSoutput$DIC
print(out.dic)
```

# Probar con las 4 ligas



# Modelo con interacciones


# Modelo con bin

# Modelo jerarquico
Modelo jerarquico
* Region
* Genero
* Con el tiempo, como los mineros


Interacción entre mes y año




