---
title: "Modelo con Interaccion"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
library(readr)
library(R2jags)
library(ggplot2)
library(dplyr)
library(readr)
library(tidyr)

#--- Usar espejo CRAN del ITAM ---
options(repos="http://cran.itam.mx/")

#--- Funciones utiles ---
prob<-function(x){
  out<-min(length(x[x>0])/length(x),length(x[x<0])/length(x))
  out
}
```


```{r}
#-Cargando los datos
datos <- read_csv("./../data/clean_rotacion.csv")

#-Definiendo las variables
n<-dim(datos)[1]

y <- datos$rotacion
experiencia <- datos$experiencia
genero <- datos$genero
dependientes <- datos$dependientes
edo_civil <- datos$edo_civil
escolaridad <- datos$escolaridad
datos$mes <- as.numeric(format(as.Date(datos$f_alta,format = "%d-%b-%y"), "%m"))
mes <- datos$mes-6
edad <- as.vector(scale(datos$edad))
num_ventas <- as.vector(scale(datos$num_ventas))
num_trabajos_previos <- as.vector(scale(datos$num_trabajos_previos))
sueldo_prom <- as.vector(scale(datos$sueldo_prom))
salario_diario_ant <- as.vector(scale(datos$salario_diario_ant))
antiguedad <- as.vector(scale(datos$antiguedad))
incremento <- as.vector(scale(datos$incremento ))
div <- datos$div

# ORDEN: Categoricas, numericas y después dev

#### MODELO SIMPLE

#-Definiendo datos-
data_1<-list("n"=n,"y"=y,"experiencia"= experiencia,
           "genero"=genero,"dependientes"=dependientes,
           "edo_civil"=edo_civil,"escolaridad"=escolaridad,
           "mes"=mes,"num_ventas"=num_ventas,
            "edad"=edad,"num_trabajos"= num_trabajos_previos,
            "sueldo_prom"=sueldo_prom, "sueldo_ant" =salario_diario_ant,
           "antiguedad" =antiguedad, "incremento"=incremento, "div"=div)

#-Definiendo inits-
inits_1<-function(){list(alpha=0,
                       b_exp=rep(0,3),b_gen=rep(0,2),
                       b_dep = rep(0,3), b_edo_c = rep(0,2),
                       b_esc = rep(0, 3), b_mes = rep(0,6), 
                       b_num_v = 0, b_edad = 0, b_num_t =0,
                       b_suel = 0, b_suel_ant = 0, b_ant = 0, 
                       b_inc = 0, b_div = rep(0,2))}

#-Seleccionando parametros a monitorear-
parameters_1<-c("alpha.est", 
              "b_exp.est", "b_gen.est", "b_dep.est", "b_edo_c.est", "b_esc.est",
              "b_mes.est", "b_num_v", "b_edad", "b_num_t","b_suel",
              "b_suel_ant", "b_ant", "b_inc", "b_div.est")

mod1.sim<-jags(data_1,inits_1,parameters_1,model.file="./../models/logit.txt",
              n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1)
out.dic1<-mod1.sim$BUGSoutput$DIC
print(out.dic1) #611.2663
out.sum1<-mod1.sim$BUGSoutput$summary
print(out.sum1)
write.csv(out.sum1,"./../results/logit_simple.csv")

mod2.sim<-jags(data_1,inits_1,parameters_1,model.file="./../models/probit.txt",
              n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1)
out.dic2<-mod2.sim$BUGSoutput$DIC
print(out.dic2) #620.3669

mod3.sim<-jags(data_1,inits_1,parameters_1,model.file="./../models/cloglog.txt",
              n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1)
out.dic3<-mod3.sim$BUGSoutput$DIC
print(out.dic3) #

#### MODELO CON INTERACCIONES


datos <- datos %>% mutate(
  grupo_edad=0,
  grupo_edad = case_when(
    edad < 30 ~  1,
    edad > 50 ~ 3,
    TRUE ~ 2
  )
)
grupo_edad <- datos$grupo_edad

datos <- datos %>% mutate(
  grupo_sueldo=0,
  grupo_sueldo = case_when(
    sueldo_prom < 2000 ~  1,
    sueldo_prom  > 10000 ~ 3,
    TRUE ~ 2
  )
)

grupo_sueldo <- datos$grupo_sueldo


#-Definiendo datos-
data_2<-list("n"=n,"y"=y,"experiencia"= experiencia,
           "genero"=genero,"dependientes"=dependientes,
           "edo_civil"=edo_civil,"escolaridad"=escolaridad,
           "mes"=mes,"num_ventas"=num_ventas,
            "edad"=grupo_edad,"num_trabajos"= num_trabajos_previos,
            "sueldo_prom"=grupo_sueldo, "sueldo_ant" =salario_diario_ant,
           "antiguedad" =antiguedad, "incremento"=incremento, "div"=div)

#-Definiendo inits-
inits_2<-function(){list(alpha=0,
                       b_exp=rep(0,3),b_gen=rep(0,2),
                       b_dep = rep(0,3), b_edo_c = rep(0,2),
                       b_esc = rep(0, 3), b_mes = rep(0,6), 
                       b_num_v = 0, b_edad = rep(0,3), b_num_t =0,
                       b_suel = rep(0,3), b_suel_ant = 0, b_ant = 0, 
                       b_inc = 0, b_div = rep(0,2), b_edad_suel = matrix(0, 3, 3))}

#-Seleccionando parametros a monitorear-
parameters_2<-c("alpha.est", 
              "b_exp.est", "b_gen.est", "b_dep.est", "b_edo_c.est", "b_esc.est",
              "b_mes.est", "b_num_v", "b_edad.est", "b_num_t","b_suel.est",
              "b_suel_ant", "b_ant", "b_inc", "b_div.est", "b_edad_suel.est")

mod21.sim<-jags(data_2,inits_2,parameters_2,model.file="./../models/logit_int.txt",
              n.iter=1000,n.chains=2,n.burnin=300,n.thin=1)
out.dic21<-mod21.sim$BUGSoutput$DIC
print(out.dic21) #¡
out.sum21<-mod21.sim$BUGSoutput$summary
write.csv(out.sum21,"./../results/logit_int.csv")

mod22.sim<-jags(data_2,inits_2,parameters_2,model.file="./../models/probit_int.txt",
              n.iter=1000,n.chains=2,n.burnin=300,n.thin=1)
out.dic22<-mod22.sim$BUGSoutput$DIC
print(out.dic22) #
out.sum22<-mod22.sim$BUGSoutput$summary
write.csv(out.sum22,"./../results/probit_int.csv")

mod23.sim<-jags(data_2,inits_2,parameters_2,model.file="./../models/cloglog_int.txt",
              n.iter=1000,n.chains=2,n.burnin=300,n.thin=1)
out.dic23<-mod23.sim$BUGSoutput$DIC
print(out.dic23) #
out.sum23<-mod23.sim$BUGSoutput$summary
write.csv(out.sum23,"./../results/cloglog_int.csv")
```


#### INTERACCIONES

```{r}
ggplot(datos, aes(x=factor(grupo_edad), fill=factor(grupo_sueldo))) +
  geom_bar(position="stack")+ 
  facet_grid(~rotacion)
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
          panel.background = element_blank(), axis.line = element_line(colour = "black"),
          axis.title = element_text(size=15), axis.text =  element_text(size=9), 
          axis.text.x = element_text(angle=0))
```


```{r}
out.sum <- out.sum23
out.est<-out.sum[grep("b_edad.est",rownames(out.sum)),]
k<-3
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="categoria",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Edad")


out.est<-out.sum[grep("b_suel.est",rownames(out.sum)),]
k<-3
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="categoria",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Sueldo")
```


```{r}
out.sum<-mod1.sim$BUGSoutput$summary

out.b_gen_div<-out.sum[grep("b_gen_div",rownames(out.sum)),]
out.est<-out.b_gen_div[c(1:2),]
k<-2
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Interaccion hospital y grado Universidad")

```


```{r}
#JAGS
out.sum<-mod1.sim$BUGSoutput$summary

#ALPHA
z<-out$alpha.est
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
title("Efecto: Alfa")

z<-out$b_num_v 
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
title("Efecto: Número ventas")

z<-out$b_num_v 
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
title("Efecto: Número ventas")


z<-out$b_edad 
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
title("Efecto: Edad")


z<-out$b_num_t 
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
title("Efecto: Número trabajos anteriores")



z<-out$b_suel
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
title("Efecto: Sueldo")


z<-out$b_suel_ant
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
title("Efecto: Sueldo anterior")

z<-out$b_ant
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
title("Efecto: Antiguedad")

z<-out$b_inc
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
title("Efecto: Incremento")


out.est<-out.sum[grep("b_exp",rownames(out.sum)),]
k<-2
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="categoria",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Experiencia")

out.est<-out.sum[grep("b_gen",rownames(out.sum)),]
k<-2
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="categoria",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Genero")


out.est<-out.sum[grep("b_dep",rownames(out.sum)),]
k<-3
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="categoria",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Dependientes")


out.est<-out.sum[grep("b_edo_c",rownames(out.sum)),]
k<-2
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="categoria",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Estado Civil")

out.est<-out.sum[grep("b_esc",rownames(out.sum)),]
k<-3
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="categoria",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Escolaridad")

out.est<-out.sum[grep("b_mes",rownames(out.sum)),]
k<-6
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="categoria",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Mes")


out.est<-out.sum[grep("b_div",rownames(out.sum)),]
k<-2
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="categoria",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Region")

```


## Interacciones

Antes de crear las interacciones podemos graficar nuestra hipotesis.

```{r}
res<-cor(datos)
round(res, 2)

library(corrplot)
corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

```


```{r}
ggplot(datos, aes(x=factor(grupo_edad), fill=factor(escolaridad))) +
  geom_bar(position="stack")+ 
  facet_grid(~rotacion)
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
          panel.background = element_blank(), axis.line = element_line(colour = "black"),
          axis.title = element_text(size=15), axis.text =  element_text(size=9), 
          axis.text.x = element_text(angle=0))
```






Comprobamos que la interacción estuvo bien implementada

```{r}
out.sum<-mod1.sim$BUGSoutput$summary


out.b_an<-out.sum[grep("b_an.est",rownames(out.sum)),]
out.est<-out.b_an
k<-2
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="dia",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Anestesia")

out.b_fn<-out.sum[grep("b_fn.est",rownames(out.sum)),]
out.est<-out.b_fn
k<-2
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="dia",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Forma Nacimiento")


out.b_an_fn<-out.sum[grep("b_an_fn.est",rownames(out.sum)),]
out.est<-out.b_an_fn[c(3,4),]
k<-2
ymin<-min(out.est[,c(1,3,7)])
ymax<-max(out.est[,c(1,3,7)])
plot(1:k,out.est[,1],xlab="",ylab="",ylim=c(ymin,ymax))
segments(1:k,out.est[,3],1:k,out.est[,7])
abline(h=0,col="grey70")
title("Efecto: Forma Nacimiento Vaginal con y sin anestesia")

```


